apiVersion: v1
kind: Pod
metadata:
  name: wildfly
  labels:
    name: wildfly
spec:
  containers:
  - name: wildfly
    image: registry.ng.bluemix.net/ihidaka/wildfly1
    ports:
    - containerPort: 9990
